### ISSUE TITLE
Syntax error in Yaml.php line 43

### ISSUE THREAD

**Issue by chocolata** [mplodowski/maillog-plugin-public#1] opened 2023-02-15 08:52 UTC
Hi,

I just bought the maillog software but there is an error when trying to sync the project on October CMS v3.

```
In Yaml.php line 43:
                                                                                                                                                                                         
  A syntax error was detected in /var/www/vhosts/domain.com/httpdocs/plugins/suresoftware/maillog/updates/version.yaml. The string "!!! 'Added in automatic mail log purging.  
   This will automatically purge mail logs that are 30 days or older by default'" could not be parsed as it uses an unsupported built-in tag at line 15 (near "2.0.0: !!! 'Added in aut  
  omatic mail log purging. This will automatically purge mail logs that are 30 days or older by default'") at line 43 (near "/var/www/vhosts/domain.com/httpdocs/vendor/octob  
  er/rain/src/Parse/Yaml.php").   
```

It is exactly the same error as was present in the Maillog by SureSoftware that is since discontinued - that is the one I'm migrating from. It's clear that this plugin is a fork from their repository, which is fine, but could you then kindly resolve the issues?

**Comment by mplodowski** [comment] 2023-02-15 09:01
Hi,

this error is caused by suresoftware plugin, not mine. Please remove it first. Then try to run sync command.

My plugin is not a fork, it is written from scratch.

**Comment by chocolata** [comment] 2023-02-15 09:17
Hi @mplodowski 

I apologize. You are correct. I overlooked that the original plugin kept installing everytime I ran the sync command. It was still present in my composer.json file. It's my fault, I should have checked better, I'm sorry.

The plugin now seems to be installed correctly.
It seems to log the mails from my contactform correctly.

There is one signup form on my site though, that includes an ICS file attachment. This seems to cause issues.
Could you kindly have a look at it?

`Call to undefined method Symfony\Component\Mime\Part\DataPart::getFilename()" on line 47 of /var/www/vhosts/domein.com/httpdocs/plugins/renatio/maillog/listeners/LogEmail.ph`

**Comment by chocolata** [comment] 2023-02-15 09:23
For your reference, this is how my mail is set up:

            Mail::send('chocolata.eventmanager::mail.rsvp', $vars, function($message) {
                $message->to(Input::get('email'),Input::get('first_name').' '.Input::get('last_name'));
                $theme = Theme::getActiveTheme();
                if($theme->ics_file) {
                    $message->attach(getenv('APP_URL').'/'.('storage/app/media'.$theme->ics_file), [
                        'as' => 'invite.ics',
                        'mime' => 'text/calendar'
                    ]);
                }

                if($theme->form_email && !empty($theme->form_email)) {
                    $message->replyTo($theme->form_email, $theme->company);
                } else {
                    $message->replyTo('myfallbackmail@domain.com', 'Chocolata');
                }
            });

**Comment by mplodowski** [comment] 2023-02-16 11:51
Hi,

it seems like you have different version of Symfony\Component\Mime\Part\DataPart file and there is no method getFilename there. Maybe this is caused by different PHP version so composer downloaded different version. I checked on PHP 8.1.

What version of PHP are you using?

**Comment by chocolata** [comment] 2023-02-16 15:37
Hi @mplodowski , thank you for your answer. I'm currently running PHP version 8.0.27.

I've updated my script to get the attachment, to no avail:

`$message->attach(storage_path('/app/media'.$theme->ics_file), ['as' => 'invite.ics', 'mime' => 'text/calendar']);`

Commenting out line 49 and 50 of listeners/LogEmail.php suppresses the error.

Do you have an idea what might be a workaround?

**Comment by mplodowski** [comment] 2023-02-16 17:55
It issue with PHP 8.0 and composer pulling older version of symfony/mime package for Laravel.

I will check if I can make it work for PHP 8.0. If not I will add a check and omit logging attachments to fix this issue.

**Comment by chocolata** [comment] 2023-02-16 22:25
Sounds perfect. Thanks for your work.

**Comment by mplodowski** [comment] 2023-03-19 17:27
It should be fixed in v1.0.5.

**Closed as completed by mplodowski** 2023-03-19 17:27 UTC

**Comment by chocolata** [comment] 2023-03-21 19:58
Hi - could it be that there might be something preventing the update? I keep getting this error message:

`The 'https://gateway.octobercms.com/composer/dist/renatio/maillog-plugin/renatio-maillog-plugin-c06afefb5c02e95aba9d94d558eb06e4e8d0bd49-zip-2fc605.zip' URL could not be accessed (HTTP 403): HTTP/1.1 403 Forbidden`

**Comment by mplodowski** [comment] 2023-03-22 07:31
Sometimes the octobercms gateway has some issues, but in this case I assume that you need to set project license again.

**Comment by chocolata** [comment] 2023-03-22 13:11
Okay, thanks a lot!
